version: '3.8'

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  server:
    build: .
    image: hanabi-server
    depends_on:
      - redis
    environment:
      # so your server can reach Redis by service name
      REDIS_HOST: redis
      REDIS_PORT: "6379"
    ports:
      - "12345:12345"